### ISSUE TITLE
log 1

### ISSUE THREAD

**Issue by tranawolf** [tranawolf/crashes#1]
[crash-2017-08-08_12.25.15-client.txt](https://github.com/tranawolf/crashes/files/1209356/crash-2017-08-08_12.25.15-client.txt)

**Comment by tranawolf** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
Contact their authors BEFORE contacting forge

// I feel sad now :(

Time: 8/8/17 12:25 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at com.saomc.SoundCore.play(SoundCore.java:43)
	at com.saomc.screens.menu.IngameMenuGUI.func_146281_b(IngameMenuGUI.java:118)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:913)
	at com.saomc.screens.menu.IngameMenuGUI.action(IngameMenuGUI.java:244)
	at com.saomc.screens.menu.IngameMenuGUI.actionPerformed(IngameMenuGUI.java:135)
	at com.saomc.screens.Elements.actionPerformed(Elements.java:107)
	at com.saomc.screens.Elements.actionPerformed(Elements.java:107)
	at com.saomc.screens.Elements.actionPerformed(Elements.java:107)
	at com.saomc.screens.Elements.actionPerformed(Elements.java:107)
	at com.saomc.screens.Elements.actionPerformed(Elements.java:107)
	at com.saomc.screens.Elements.actionPerformed(Elements.java:107)
	at com.saomc.screens.ContainerGUI.mouseReleased(ContainerGUI.java:80)
	at com.saomc.screens.window.ScreenGUI.func_146286_b(ScreenGUI.java:190)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:565)
	at com.saomc.screens.window.ScreenGUI.func_146274_d(ScreenGUI.java:209)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.saomc.SoundCore.play(SoundCore.java:43)
	at com.saomc.screens.menu.IngameMenuGUI.func_146281_b(IngameMenuGUI.java:118)
	at net.minecraft.client.Minecraft.func_147108_a(Minecraft.java:913)
	at com.saomc.screens.menu.IngameMenuGUI.action(IngameMenuGUI.java:244)
	at com.saomc.screens.menu.IngameMenuGUI.actionPerformed(IngameMenuGUI.java:135)
	at com.saomc.screens.Elements.actionPerformed(Elements.java:107)
	at com.saomc.screens.Elements.actionPerformed(Elements.java:107)
	at com.saomc.screens.Elements.actionPerformed(Elements.java:107)
	at com.saomc.screens.Elements.actionPerformed(Elements.java:107)
	at com.saomc.screens.Elements.actionPerformed(Elements.java:107)
	at com.saomc.screens.Elements.actionPerformed(Elements.java:107)
	at com.saomc.screens.ContainerGUI.mouseReleased(ContainerGUI.java:80)
	at com.saomc.screens.window.ScreenGUI.func_146286_b(ScreenGUI.java:190)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:565)
	at com.saomc.screens.window.ScreenGUI.func_146274_d(ScreenGUI.java:209)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:524)

-- Affected screen --
Details:
	Screen name: com.saomc.screens.menu.IngameMenuGUI
Stacktrace:
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1674)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1024)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:349)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Mac OS X (x86_64) version 10.12.6
	CPU: 4x Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3183339168 bytes (3035 MB) / 3487563776 bytes (3326 MB) up to 7874281472 bytes (7509 MB)
	JVM Flags: 3 total; -Xmx8448m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 99
	FML: MCP 9.19 Powered by Forge 11.15.1.2318 Optifine OptiFine_1.8.9_HD_U_H8 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	Forge{11.15.1.2318} [Minecraft Forge] (forge-1.8.9-11.15.1.2318-1.8.9.jar) 
	UCHIJA	CustomMainMenu{2.0} [Custom Main Menu] (CustomMainMenu-MC1.8.9-2.0.jar) 
	UCHIJA	itemscroller{0.5.1} [Item Scroller] (itemscroller-1.8.9-0.5.1.jar) 
	UCHIJA	journeymap{1.8.9-5.2.4} [JourneyMap] (journeymap-1.8.9-5.2.4-unlimited.jar) 
	UCHIJA	ResourceLoader{1.4} [Resource Loader] (ResourceLoader-MC1.8.8-1.4.jar) 
	UCHIJA	saoui{1.8.9-1.6.0-Dev1} [Sword Art Online UI] (saoui-1.8.9-1.6.0.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (ResourceLoader-MC1.8.8-1.4.jar)
  lumien.resourceloader.asm.ClassTransformer
	Launched Version: forge-11.15.1.2318
	LWJGL: 2.9.2
	OpenGL: Intel HD Graphics 4000 OpenGL Engine GL version 2.1 INTEL-10.25.17, Intel Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-3427U CPU @ 1.80GHz
	The 5zig Mod Version: 3.11.7
	The 5zig Mod Plugins: []
	Forge: true
	GUI: ~~NULL~~
	OptiFine Version: OptiFine_1.8.9_HD_U_H8
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 2.1 INTEL-10.25.17
	OpenGlRenderer: Intel HD Graphics 4000 OpenGL Engine
	OpenGlVendor: Intel Inc.
	CpuCount: 4
